active_theme: dark
border_radius: 10
font: Arial
height: 900
last_open_file:
- C:/Users/HP/Desktop/my project/UI++/Log GUI/test.log
log_text_colors:
  critical:
  - '#ff0000'
  - true
  debug:
  - '#00ff00'
  - false
  error:
  - '#ff7000'
  - true
  fatal:
  - '#ffff00'
  - false
  info:
  - '#009ce8'
  - false
  warning:
  - '#ffb842'
  - true
size: 14
width: 1500
